### PR TITLE
Added option for user to show map location for stores.

### PR DESCRIPTION
**Pull request by tjtanjin**
Added an option for users to get map location of stores. There might be certain stores that do not have the most accurate map location but this can be improved overtime :D

### CODE REVIEW

**Comment by gau-nernst** [comment]
I have tested the new code and it seems to work fine. Some concerns I have observed:
- Is pinpoint longitude latitude information useful for the user? @gabztcr @picasdan9 can help confirm this by using the feature yourself
- Validity of longitude latitude information

**Code style**: since we are using pandas to manage the excel file, I would prefer if @tjtanjin can use pandas dataframe indexing/query instead of creating a separate dictionary for location. e.g.

```python
location = opening_hours[opening_hours.Store == store].iloc[0]
```

Latitude and Longitude can be put as separate columns in the excel file also.

Let me know what you think by commeting below. Thanks

**Comment by tjtanjin** [comment]
Hello! Thank you for the quick review.

I have updated the code style to use pandas df instead and placed latitude and longitude into separate columns. Regarding your 2 concerns, my personal views are as below:

- The usefulness of map location is likely to depend on the user's familiarity with the stores in UTown. As for whether this is then really necessary, I leave it to you and your team to decide.

- There are likely some locations where the latitude and longitude is not the most accurate. On this note, would you think that having a command like /feedback for users to flag out errors in information (location, opening hours etc) would be useful for faster corrections?

Thank you!

**Comment by dannn-tran** [comment]
Hi,

I think this added feature could be useful. Pertaining to functionality, the purpose is to show how to navigate to the place. However, using latitude and longitude with Google Maps seems to be problematic due to the imprecise pinpointing of location e.g. location of Cheers is taken to be of CREATE building. 

My suggestion: use a static image of NUS UTown map. When the user queries for a store, return the image with that store highlighted on the map. Also include info like which level the store is on and in which building. We'll then either have lots of images of utown maps with various stores highlighted, or write code to do the highlighting. The former should give faster response time.

**Comment by tjtanjin** [comment]
Hello,

I noticed the issue of locations being unspecific. I have changed the approach to provide a google maps link instead of using latitude and longitude so majority of the locations now are more specific (there are still a few that cannot be found on google maps). The downside is that there is a popup confirmation before the link is open on google maps but I feel it is worth the more specific location provided. Please share your thoughts, thank you!

**Review by gau-nernst — APPROVED** [review]
Merge to master branch. Add Google Maps button

**Pull request merged**
